name: CI/CD

env:
    ENVIRONMENT: DEV

on:
  push:
    branches: [feature_5.0]
       
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: 'Create .env file'
        run: |
         touch .env
         ENVIRONMENT: DEV
         PORT: 8080
         DATABASE: jarvis
         HOSTNAME: localhost
         DBUSER: jarvis
         DBPASSWORD=Rohit@123
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
  
          