name: CI/CD

on:
  push:
    branches: [feature_5.0]
       
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]
    
    steps:
        - uses: actions/checkout@v3
        - name: 'Create .env file'
          run: |
                touch .env
                echo ENVIRONMENT: DEV
                echo PORT: 8080
                echo DATABASE: jarvis
                echo HOSTNAME: localhost
                echo DBUSER: jarvis
                echo DBPASSWORD=Rohit@123
        - name: Set up PostgreSQL
          run: |
            docker run --name jarvis -e DBPASSWORD=Rohit@123 -d -p 5432:5432 postgres:13
        - name: Wait for PostgreSQL to start
          run: |
              for i in {1..30}; do
                pg_isready -h localhost -p 5432 -U postgres && break
                sleep 5
              done

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
                node-version: ${{ matrix.node-version }}
        - run: yarn
        - run: yarn test
  
          