name: Integration Tests

on:
  push:
    branches: 
      - feature_5.0 # Assuming your primary branch is named 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: jarvis
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: "Create env file"
        run: |
          touch .env
          echo PGDATABASE=jarvis >> .env
          echo PGUSER=postgres >> .env
          echo PGPASSWORD=postgres >> .env
          echo PGPORT=5432 >> .env
          echo PGHOST=localhost >> .env
          echo "cat .env"
          cat .env
          echo "ls -a ."
          ls -a .

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x # Assuming you are using Node.js. Change this accordingly.

      - name: Install Dependencies
        run: npm install # chekcout to directory, touch a enc file, pull all secrets

      - name: Run Integration Tests
        run: npm test # Assuming you have a script in your package.json named "test:integration" that runs your integration tests.